services:
  api:
    build: api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build: app
    ports:
      - "8000:80"
    depends_on:
      - api
  
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "autocc"
      POSTGRES_USER: "autocc"
      POSTGRES_PASSWORD: "autocc"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autocc"]
      interval: 10s
      timeout: 10s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USER: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KC_BOOTSTRAP_REALM: "autocc"
    command: start-dev
