// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pkulik0/autocc/api/internal/youtube (interfaces: Youtube)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/youtube.go -package=mocks . Youtube
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pb "github.com/pkulik0/autocc/api/internal/pb"
	gomock "go.uber.org/mock/gomock"
)

// MockYoutube is a mock of Youtube interface.
type MockYoutube struct {
	ctrl     *gomock.Controller
	recorder *MockYoutubeMockRecorder
}

// MockYoutubeMockRecorder is the mock recorder for MockYoutube.
type MockYoutubeMockRecorder struct {
	mock *MockYoutube
}

// NewMockYoutube creates a new mock instance.
func NewMockYoutube(ctrl *gomock.Controller) *MockYoutube {
	mock := &MockYoutube{ctrl: ctrl}
	mock.recorder = &MockYoutubeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYoutube) EXPECT() *MockYoutubeMockRecorder {
	return m.recorder
}

// GetMetadata mocks base method.
func (m *MockYoutube) GetMetadata(arg0 context.Context, arg1, arg2 string) (*pb.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", arg0, arg1, arg2)
	ret0, _ := ret[0].(*pb.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockYoutubeMockRecorder) GetMetadata(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockYoutube)(nil).GetMetadata), arg0, arg1, arg2)
}

// GetVideos mocks base method.
func (m *MockYoutube) GetVideos(arg0 context.Context, arg1, arg2 string) ([]*pb.Video, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideos", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*pb.Video)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVideos indicates an expected call of GetVideos.
func (mr *MockYoutubeMockRecorder) GetVideos(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideos", reflect.TypeOf((*MockYoutube)(nil).GetVideos), arg0, arg1, arg2)
}
