// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: pb/autocc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCredentialsGoogleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId     string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
}

func (x *AddCredentialsGoogleRequest) Reset() {
	*x = AddCredentialsGoogleRequest{}
	mi := &file_pb_autocc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialsGoogleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialsGoogleRequest) ProtoMessage() {}

func (x *AddCredentialsGoogleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autocc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialsGoogleRequest.ProtoReflect.Descriptor instead.
func (*AddCredentialsGoogleRequest) Descriptor() ([]byte, []int) {
	return file_pb_autocc_proto_rawDescGZIP(), []int{0}
}

func (x *AddCredentialsGoogleRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AddCredentialsGoogleRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type CredentialsGoogle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId     string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	Usage        uint64 `protobuf:"varint,4,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *CredentialsGoogle) Reset() {
	*x = CredentialsGoogle{}
	mi := &file_pb_autocc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsGoogle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsGoogle) ProtoMessage() {}

func (x *CredentialsGoogle) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autocc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsGoogle.ProtoReflect.Descriptor instead.
func (*CredentialsGoogle) Descriptor() ([]byte, []int) {
	return file_pb_autocc_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialsGoogle) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CredentialsGoogle) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CredentialsGoogle) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CredentialsGoogle) GetUsage() uint64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

type AddCredentialsGoogleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credentials *CredentialsGoogle `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
}

func (x *AddCredentialsGoogleResponse) Reset() {
	*x = AddCredentialsGoogleResponse{}
	mi := &file_pb_autocc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialsGoogleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialsGoogleResponse) ProtoMessage() {}

func (x *AddCredentialsGoogleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autocc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialsGoogleResponse.ProtoReflect.Descriptor instead.
func (*AddCredentialsGoogleResponse) Descriptor() ([]byte, []int) {
	return file_pb_autocc_proto_rawDescGZIP(), []int{2}
}

func (x *AddCredentialsGoogleResponse) GetCredentials() *CredentialsGoogle {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type AddCredentialsDeepLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AddCredentialsDeepLRequest) Reset() {
	*x = AddCredentialsDeepLRequest{}
	mi := &file_pb_autocc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialsDeepLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialsDeepLRequest) ProtoMessage() {}

func (x *AddCredentialsDeepLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autocc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialsDeepLRequest.ProtoReflect.Descriptor instead.
func (*AddCredentialsDeepLRequest) Descriptor() ([]byte, []int) {
	return file_pb_autocc_proto_rawDescGZIP(), []int{3}
}

func (x *AddCredentialsDeepLRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CredentialsDeepL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Usage uint64 `protobuf:"varint,3,opt,name=usage,proto3" json:"usage,omitempty"`
}

func (x *CredentialsDeepL) Reset() {
	*x = CredentialsDeepL{}
	mi := &file_pb_autocc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialsDeepL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialsDeepL) ProtoMessage() {}

func (x *CredentialsDeepL) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autocc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialsDeepL.ProtoReflect.Descriptor instead.
func (*CredentialsDeepL) Descriptor() ([]byte, []int) {
	return file_pb_autocc_proto_rawDescGZIP(), []int{4}
}

func (x *CredentialsDeepL) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CredentialsDeepL) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CredentialsDeepL) GetUsage() uint64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

type AddCredentialsDeepLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Credentials *CredentialsDeepL `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
}

func (x *AddCredentialsDeepLResponse) Reset() {
	*x = AddCredentialsDeepLResponse{}
	mi := &file_pb_autocc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCredentialsDeepLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCredentialsDeepLResponse) ProtoMessage() {}

func (x *AddCredentialsDeepLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autocc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCredentialsDeepLResponse.ProtoReflect.Descriptor instead.
func (*AddCredentialsDeepLResponse) Descriptor() ([]byte, []int) {
	return file_pb_autocc_proto_rawDescGZIP(), []int{5}
}

func (x *AddCredentialsDeepLResponse) GetCredentials() *CredentialsDeepL {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type GetCredentialsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Google []*CredentialsGoogle `protobuf:"bytes,1,rep,name=google,proto3" json:"google,omitempty"`
	Deepl  []*CredentialsDeepL  `protobuf:"bytes,2,rep,name=deepl,proto3" json:"deepl,omitempty"`
}

func (x *GetCredentialsResponse) Reset() {
	*x = GetCredentialsResponse{}
	mi := &file_pb_autocc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialsResponse) ProtoMessage() {}

func (x *GetCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_autocc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_pb_autocc_proto_rawDescGZIP(), []int{6}
}

func (x *GetCredentialsResponse) GetGoogle() []*CredentialsGoogle {
	if x != nil {
		return x.Google
	}
	return nil
}

func (x *GetCredentialsResponse) GetDeepl() []*CredentialsDeepL {
	if x != nil {
		return x.Deepl
	}
	return nil
}

var File_pb_autocc_proto protoreflect.FileDescriptor

var file_pb_autocc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x63, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x5f, 0x0a, 0x1b, 0x41, 0x64, 0x64, 0x43, 0x72, 0x65, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x7b, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x75, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x57, 0x0a, 0x1c, 0x41, 0x64, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x73, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x52,
	0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x2e, 0x0a, 0x1a,
	0x41, 0x64, 0x64, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x44, 0x65,
	0x65, 0x70, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x4a, 0x0a, 0x10,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x44, 0x65, 0x65, 0x70, 0x4c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x75, 0x73, 0x61, 0x67, 0x65, 0x22, 0x55, 0x0a, 0x1b, 0x41, 0x64, 0x64, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x44, 0x65, 0x65, 0x70, 0x4c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x44, 0x65, 0x65,
	0x70, 0x4c, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22,
	0x73, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x47, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x52, 0x06, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x64, 0x65, 0x65, 0x70,
	0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x44, 0x65, 0x65, 0x70, 0x4c, 0x52, 0x05, 0x64,
	0x65, 0x65, 0x70, 0x6c, 0x42, 0x5f, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x62, 0x42, 0x0b,
	0x41, 0x75, 0x74, 0x6f, 0x63, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x20, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6b, 0x75, 0x6c, 0x69, 0x6b,
	0x30, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x63, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0xa2,
	0x02, 0x03, 0x50, 0x58, 0x58, 0xaa, 0x02, 0x02, 0x50, 0x62, 0xca, 0x02, 0x02, 0x50, 0x62, 0xe2,
	0x02, 0x0e, 0x50, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x02, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_autocc_proto_rawDescOnce sync.Once
	file_pb_autocc_proto_rawDescData = file_pb_autocc_proto_rawDesc
)

func file_pb_autocc_proto_rawDescGZIP() []byte {
	file_pb_autocc_proto_rawDescOnce.Do(func() {
		file_pb_autocc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_autocc_proto_rawDescData)
	})
	return file_pb_autocc_proto_rawDescData
}

var file_pb_autocc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_autocc_proto_goTypes = []any{
	(*AddCredentialsGoogleRequest)(nil),  // 0: pb.AddCredentialsGoogleRequest
	(*CredentialsGoogle)(nil),            // 1: pb.CredentialsGoogle
	(*AddCredentialsGoogleResponse)(nil), // 2: pb.AddCredentialsGoogleResponse
	(*AddCredentialsDeepLRequest)(nil),   // 3: pb.AddCredentialsDeepLRequest
	(*CredentialsDeepL)(nil),             // 4: pb.CredentialsDeepL
	(*AddCredentialsDeepLResponse)(nil),  // 5: pb.AddCredentialsDeepLResponse
	(*GetCredentialsResponse)(nil),       // 6: pb.GetCredentialsResponse
}
var file_pb_autocc_proto_depIdxs = []int32{
	1, // 0: pb.AddCredentialsGoogleResponse.credentials:type_name -> pb.CredentialsGoogle
	4, // 1: pb.AddCredentialsDeepLResponse.credentials:type_name -> pb.CredentialsDeepL
	1, // 2: pb.GetCredentialsResponse.google:type_name -> pb.CredentialsGoogle
	4, // 3: pb.GetCredentialsResponse.deepl:type_name -> pb.CredentialsDeepL
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_autocc_proto_init() }
func file_pb_autocc_proto_init() {
	if File_pb_autocc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_autocc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_autocc_proto_goTypes,
		DependencyIndexes: file_pb_autocc_proto_depIdxs,
		MessageInfos:      file_pb_autocc_proto_msgTypes,
	}.Build()
	File_pb_autocc_proto = out.File
	file_pb_autocc_proto_rawDesc = nil
	file_pb_autocc_proto_goTypes = nil
	file_pb_autocc_proto_depIdxs = nil
}
