// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pkulik0/autocc/api/internal/youtube (interfaces: Youtube)
//
// Generated by this command:
//
//	mockgen -destination=../mock/youtube.go -package=mock . Youtube
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	pb "github.com/pkulik0/autocc/api/internal/pb"
	srt "github.com/pkulik0/autocc/api/internal/srt"
	youtube "github.com/pkulik0/autocc/api/internal/youtube"
	gomock "go.uber.org/mock/gomock"
)

// MockYoutube is a mock of Youtube interface.
type MockYoutube struct {
	ctrl     *gomock.Controller
	recorder *MockYoutubeMockRecorder
	isgomock struct{}
}

// MockYoutubeMockRecorder is the mock recorder for MockYoutube.
type MockYoutubeMockRecorder struct {
	mock *MockYoutube
}

// NewMockYoutube creates a new mock instance.
func NewMockYoutube(ctrl *gomock.Controller) *MockYoutube {
	mock := &MockYoutube{ctrl: ctrl}
	mock.recorder = &MockYoutubeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYoutube) EXPECT() *MockYoutubeMockRecorder {
	return m.recorder
}

// DownloadCC mocks base method.
func (m *MockYoutube) DownloadCC(ctx context.Context, userID, ccID string) (*srt.Srt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadCC", ctx, userID, ccID)
	ret0, _ := ret[0].(*srt.Srt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadCC indicates an expected call of DownloadCC.
func (mr *MockYoutubeMockRecorder) DownloadCC(ctx, userID, ccID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadCC", reflect.TypeOf((*MockYoutube)(nil).DownloadCC), ctx, userID, ccID)
}

// GetCC mocks base method.
func (m *MockYoutube) GetCC(ctx context.Context, userID, videoID string) ([]*youtube.CC, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCC", ctx, userID, videoID)
	ret0, _ := ret[0].([]*youtube.CC)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCC indicates an expected call of GetCC.
func (mr *MockYoutubeMockRecorder) GetCC(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCC", reflect.TypeOf((*MockYoutube)(nil).GetCC), ctx, userID, videoID)
}

// GetMetadata mocks base method.
func (m *MockYoutube) GetMetadata(ctx context.Context, userID, videoID string) (*youtube.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, userID, videoID)
	ret0, _ := ret[0].(*youtube.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockYoutubeMockRecorder) GetMetadata(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockYoutube)(nil).GetMetadata), ctx, userID, videoID)
}

// GetVideos mocks base method.
func (m *MockYoutube) GetVideos(ctx context.Context, userID, nextPageToken string) ([]*pb.Video, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideos", ctx, userID, nextPageToken)
	ret0, _ := ret[0].([]*pb.Video)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVideos indicates an expected call of GetVideos.
func (mr *MockYoutubeMockRecorder) GetVideos(ctx, userID, nextPageToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideos", reflect.TypeOf((*MockYoutube)(nil).GetVideos), ctx, userID, nextPageToken)
}

// UpdateMetadata mocks base method.
func (m *MockYoutube) UpdateMetadata(ctx context.Context, userID, videoID string, metadata map[string]*youtube.Metadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetadata", ctx, userID, videoID, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetadata indicates an expected call of UpdateMetadata.
func (mr *MockYoutubeMockRecorder) UpdateMetadata(ctx, userID, videoID, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetadata", reflect.TypeOf((*MockYoutube)(nil).UpdateMetadata), ctx, userID, videoID, metadata)
}

// UploadCC mocks base method.
func (m *MockYoutube) UploadCC(ctx context.Context, userID, videoID, language string, srt *srt.Srt) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadCC", ctx, userID, videoID, language, srt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadCC indicates an expected call of UploadCC.
func (mr *MockYoutubeMockRecorder) UploadCC(ctx, userID, videoID, language, srt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadCC", reflect.TypeOf((*MockYoutube)(nil).UploadCC), ctx, userID, videoID, language, srt)
}
